name = "client"
version = "1.0.0"
description = "HTTP/2 & HTTP/1 gleam HTTP client"
licences = ["Apache-2.0"]
repository = { type = "github", user = "vshakitskiy", repo = "" }
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
